import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    'EnergyEase/introduction',
    'EnergyEase/release-notes',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Getting Started',
        description:
          "Get started with Energy Ease by installing the app, creating your account, and setting up your first device.",
      },
      items: [
        'EnergyEase/installation',
        'EnergyEase/registration-login',
        'EnergyEase/add-device'
      ],
    },
    {
      type: 'category',
      label: 'Using EnergyEase',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Using EnergyEase',
        description:
          "This section walks through key functions, from energy monitoring to personal settings."
      },
      items: [
        'EnergyEase/home',
        'EnergyEase/report',
        'EnergyEase/smart',
        'EnergyEase/device',
        'EnergyEase/profile'
      ],
    },
    'EnergyEase/faq'
  ],
  
};

export default sidebars;
